name: check_branch_name
description: "Checks a branch name for validity"

inputs:
  branchName:
    description: "Name of branch"
    required: true
  debug:
    description: "Whether to debug the script"
    required: false
outputs:
  valid:
    description: "Whether the branch name is valid according to branch naming convention"
    value: ${{steps.check_branch.outputs.is_valid}}
runs:
  using: "composite"

  steps:

    - name: check branch
      id: check_branch
      shell: bash
      env:
        BRANCH_NAME: ${{inputs.branchName}}
        DEBUG: ${{inputs.debug}}
      run: |
        local is_valid=$(echo ./check_branch_name.sh)
        echo "is_valid=${is_valid}" >> $GITHUB_OUTPUT
