name: check_branch_name
description: "Checks a branch name for validity"

inputs:
  branchName:
    description: "Name of branch"
    required: true
  debug:
    description: "Whether to debug the script"
    required: false
outputs:
  valid:
    description: "Whether the branch name is valid according to branch naming convention"
    value: ${{steps.check_branch.outputs.valid}}
runs:
  using: "composite"

  steps:

    - name: check branch
      id: check_branch
      shell: bash
      env:
        BRANCH_NAME: ${{inputs.branchName}}
        DEBUG: ${{inputs.debug}}
      run: |
        name=$(echo "${{github.action_path}}" | xargs -I% basename %)
        file=$(find "${{github.workspace}}" -type f -name "$basename*" | head -1)
        if [[ -z "${file}" ]]; then
          echo "found no file to execute"
          exit 1
        fi

        echo "valid=$(bash $file)" >> $GITHUB_OUTPUT
