name: check_branch_name
description: "Checks a branch name for validity"

inputs:
  branchName:
    description: "Name of branch"
    required: true
  debug:
    description: "Whether to debug the script"
    required: false
outputs:
  valid:
    description: "Whether the branch name is valid according to branch naming convention"
    value: ${{steps.check_branch.outputs.valid}}
runs:
  using: "composite"

  steps:

    - name: check branch
      id: check_branch
      shell: bash
      env:
        BRANCH_NAME: ${{inputs.branchName}}
        DEBUG: ${{inputs.debug}}
      run: |
<<<<<<< HEAD
<<<<<<< HEAD
        basename=$(echo "${{github.action_path}}" | xargs -I% basename %)
        file=$(find "${{github.workspace}}" -type f -name "$basename*" | head -1)
        if [[ -z "${file}" ]]; then
          echo "found no file to execute"
          exit 1
        fi

        echo "valid=$(bash $file)" >> $GITHUB_OUTPUT
=======
        path=${{github.action_path}}
        valid=$(./$path/check_branch_name.sh)
        echo "valid=${valid}" >> $GITHUB_OUTPUT
>>>>>>> parent of 42fcc27... debug #8
=======
        ls -la
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        echo '${{ toJSON(github) }}'
        #valid=$(./check_branch_name.sh)
        #echo "valid=${valid}" >> $GITHUB_OUTPUT
>>>>>>> parent of 15dbb74... debug #7
=======
        echo ${{ toJSON(github) }}
=======
        echo ${{ fromJSON(github) }}
>>>>>>> parent of e3d3862... debug #4
=======
        echo ${{github}}
>>>>>>> parent of 256cd9e... debug #3
        valid=$(./check_branch_name.sh)
        echo "valid=${valid}" >> $GITHUB_OUTPUT
>>>>>>> parent of 4b82917... debug #6
