name: check_branch_name
description: "Checks a branch name for validity"

inputs:
  debug:
    description: "Whether to debug the script"
    required: false

runs:
  using: "composite"

  steps:

    - name: get ref to check
      id: get_ref
      shell: bash
      run: |
        refName=
        if [[ "${{github.event_name}}" == "push" ]]; then
          refName="${{ github.ref_name }}"
        else
          refName="${{ github.head_ref }}"
        fi
        echo "refName=${refName}" >> $GITHUB_OUTPUT

    - name: check branch
      id: check_branch
      shell: bash
      env:
        REF_NAME: ${{steps.get_ref.outputs.refName}}
        DEBUG: ${{inputs.debug}}
      run: |
        basename=$(echo "${{github.action_path}}" | xargs -I% basename %)
        file=$(find "${{github.workspace}}" -type f -name "$basename*" | head -1)
        if [[ -z "${file}" ]]; then
          echo "found no file to execute"
          exit 1
        fi

        bash $file