name: sync_azure_db
description: "Synchronizes the databases in Azure"

inputs:
  k8s_namespace:
    description: "K8s namespace running postgres-client pod"
    required: true

runs:
  using: "composite"
  steps:
    - name: sync_azure_db
      env:
        K8S_NAMESPACE: ${{inputs.k8s_namespace}}
        SOURCE_DB_HOST: old_db.efa-fhb.nortal-internal
        TARGET_DB_HOST: azure-db.efa-fhb.nortal-internal
      shell: bash
      run: bash ${{github.action_path}}/sync_azure_db.sh
