name: docker_push_image
description: "Pushes a container image with Docker"

inputs:
  images:
    description: "Docker images to push"
    required: true
runs:
  using: "composite"

  steps:

    - name: Push images
      id: push_images
      shell: bash
      env:
        images: ${{ inputs.images }}
      run: |
        echo '### Pushed Docker Images' >> $GITHUB_STEP_SUMMARY

        for image in ${{ env.images }}; do {
          docker push $image
          echo "- **$image**" >> $GITHUB_STEP_SUMMARY
        } done