name: import_container_images
description: "Fetches a list of container images from one container registry and imports them to another"

inputs:
  token:
    description: "Token used for authenticating against Github Rest API"
    required: true
  repo:
    description: "Name of repository"
    required: true
  retain-max-days:
    description: "Number of days to keep records of workflow runs."
    required: false
    default: "30"

runs:
  steps:
    - name: import_container_images
      env:
        REPOSITORY: ${{inputs.repo}}
        TOKEN: ${{inputs.token}}
        RETAIN_MAX_DAYS: ${{inputs.retain-max-days}}
      shell: bash
      run: bash ${{github.action_path}}/import_container_images.sh
