name: create_image_tag_names
description: "Create image tags based on branch name input"

inputs:
  refName:
    description: "Name of git ref (branch or tag)"
    required: true
  buildNumber:
    description: "Number of the build run"
    required: true
  semver:
    description: "String in semantic versioning format"
    required: true
  debug:
    description: "Whether to debug the script"
    required: false

outputs:
  tags:
    description: "Space separated list of image tags"
    value: ${{steps.create_image_tags.outputs.tags}}
runs:
  using: "composite"

  steps:

    - name: create image tags
      id: create_image_tags
      shell: bash
      env:
        REF_NAME: ${{inputs.refName}}
        SEMVER: ${{inputs.semver}}
        BUILD_NUMBER: ${{inputs.buildNumber}}
        DEBUG: ${{inputs.debug}}
      run: |
        basename=$(echo "${{github.action_path}}" | xargs -I% basename %)
        file=$(find "${{github.workspace}}" -type f -name "$basename*" | head -1)
        if [[ -z "${file}" ]]; then
          echo "found no file to execute"
          exit 1
        fi

        tags=
        tags=$(bash $file)
        exit_code="$?"
        echo "tags=$(bash $file)" >> $GITHUB_OUTPUT
        exit $exit_code



