name: docker_build_push_image
description: "Builds, tags, scans and pushes Docker container images"

inputs:
  image:
    description: "Value to use as name of Docker container image"
    required: true
  imageTags:
    description: "Tags used for tagging the image"
    required: true
  context:
    description: "Path to use as docker build context"
    required: true
  dockerfilePath:
    description: "Path of DockerFile"
    required: true
  scanImage:
    description: "Scan image for vulnerabilities"
    required: false
    default: "true"
  pushImage:
    description: "Whether to push docker images"
    required: false
    default: "true"
  buildArgs:
    description: "List of build-args to pass to docker build"
    required: false

outputs:
  digest:
    description: "SHA-Digest of created image"
    value: "${{ steps.build_image.outputs.digest }}"
  tags:
    description: "Space separated list of tags associated with SHA-Digest of created images"
    value: "${{ steps.prepare_push.outputs.tags }}"
runs:
  using: "composite"
  steps:

    - name: get primary tag
      id: tag_for_metadata
      shell: bash
      run: |
        IFS=" " read -r -a parts <<<"${{inputs.imageTags}}"
        echo "tag=${parts[0]}" >> $GITHUB_OUTPUT

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{inputs.image}}
        tags: |
          type=raw,value=${{steps.tag_for_metadata.outputs.tag}}

    - name: Build and push
      id: build_image
      uses: docker/build-push-action@v3
      with:
        context: ${{inputs.context}}
        file: ${{inputs.dockerFilePath}}
        push: false #do not push here
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.buildArgs }}

    - name: Apply additional tags
      id: prepare_push
      shell: bash
      run: |
        set -x
        cat <<EOF > meta.json
          ${{steps.meta.outputs.json}}
        EOF

        origImage=$(cat meta.json | jq ".tags[0]" | tr -d '"')
        images=()

        origTag=$(echo "${origImage}" | cut -d ":" -f2)

        IFS=" " read -r -a imageTags <<<"${{inputs.imageTags}}"

        for newTag in ${imageTags[*]}; do {
          newImage="${origImage/$origTag/$newTag}"
          docker tag "${origImage}" "${newImage}"
          images+=("${newImage}")
        } done

        echo "images=${images[*]}" >> $GITHUB_OUTPUT
        echo "image=${origImage}" >> $GITHUB_OUTPUT
        echo "tags=${imageTags}" >> $GITHUB_OUTPUT

    - name: Scan image for vulnerabilities
      if: ${{inputs.scanImage != 'false' }}
      shell: bash
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image \
          --ignore-unfixed \
          --exit-code 1 \
          --severity HIGH,CRITICAL \
          --reset \
          --scanners vuln ${{steps.prepare_push.outputs.image}}

    - name: Push images
      if: ${{inputs.pushImage != 'false' }}
      id: push_images
      shell: bash
      env:
        images: ${{ steps.prepare_push.outputs.images }}
      run: |
        echo '### Pushed Docker Images' >> $GITHUB_STEP_SUMMARY

        for image in ${{ env.images }}; do {
          docker push $image
          echo "- **$image**" >> $GITHUB_STEP_SUMMARY
        } done