name: cleanup_workflow_runs
description: "Deletes old workflow run"

inputs:
  token:
    description: "Token used for authenticating against Github Rest API"
    required: true
  repo:
    description: "Name of repository"
    required: true
  retain-max-run-count:
    description: "Number of runs to keep."
    required: false
    default: "30"

runs:
  using: "composite"
  steps:
    - name: delete_workflow_runs
      env:
        REPOSITORY: ${{inputs.repo}}
        TOKEN: ${{inputs.token}}
        RETAIN_MAX_RUN_COUNT: ${{inputs.retain-max-run-count}}
      shell: bash
      run: bash ${{github.action_path}}/cleanup_workflow_runs.sh
