name: is_docker_push_allowed
description: "Checks the Github environment to determine if a Docker image can be pushed"

outputs:
  result:
    description: "Indicator of whether the image can be pushed"
    value: "${{ steps.set_result.outputs.value }}"


runs:
  using: "composite"

  steps:
    - name: check ref
      id: check_ref
      shell: bash
      continue-on-error: true
      run: |
        [[ $(printenv PUSH_IMAGE) == "true" ]] && exit 0;
        [[ $(printenv GITHUB_REF) =~ main|release/.+|tags/.+ ]] && exit 0;
        exit 1;

    - name: set result
      id: set_result
      if: ${{always()}}
      shell: bash
      run: |
        if [[ ${{ steps.check_ref.outcome }} == 'success' ]]; then
          echo "::set-output name=result::true"
        else
          echo "::set-output name=result::false"
        fi
