name: create_release
description: "Creates a release"

inputs:
  token:
    description: "Token required to trigger the workflow."
    required: true
  draft:
    description: "Indicator of whether or not this release is a draft"
    required: false
  prerelease:
    description: "Indicator of whether or not is a prerelease"
    required: false
  name:
    description: "Name of the release. defaults to tag name"
    required: false
  semver_type:
    description: "Indicator of the release type"
    required: true

runs:
  using: "composite"

  steps:

    - name: changelog config template
      id: changelog_config_path
      shell: bash
      run: |
        config_path=$(find . -name "changelog-config.json" | head -1)
        echo $config_path
        echo "::set-output name=value::${config_path}"

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        configuration: ${{steps.changelog_config_path.outputs.value}}

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        draft: ${{inputs.draft}}
        prerelease: ${{inputs.draft}}
        name: ${{inputs.name}}
        body: ${{steps.github_release.outputs.changelog}}
