# This workflow creates a release for the application.
#
name: "Sync postgres databases"

on:
  workflow_dispatch:
  #schedule:
  # - cron: "0 0 * * *"

env:
  AZURE_SUBSCRIPTION_ID: 1d49c337-1058-4fe0-997f-fb7263956e13
  AZURE_RESOURCE_GROUP: oe-vergabe-dev
  AZURE_RESOURCE_NAME: efa-bremen-oeffentliche-vergabe-dev

concurrency:
  group: sync_dbs

jobs:

  sync_postgres_dbs:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        #stage: [dev, test, preview]
        stage: [dev]

    name: "🛠️ sync_dbs_on_${{matrix.stage}}"

    steps:

      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_EFA_FHB_SP_AAD_CREDENTIALS }}

      - name: set subscription
        shell: bash
        run: |
          az account set -n ${{env.AZURE_SUBSCRIPTION_ID}}

      - name: get kubelogin
        shell: bash
        run: |
          where="~/tmp/${RANDOM}"
          mkdir -p ${where}
          wget -q -P ${where} https://github.com/Azure/kubelogin/releases/download/v0.0.20/kubelogin-linux-amd64.zip
          unzip ${where}/kubelogin-linux-amd64.zip -d ${where}
          sudo mv ${where}/bin/linux_amd64/kubelogin /usr/bin

      - name: get K8s credentials + login
        shell: bash
        env:
          AAD_SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.AZURE_EFA_FHB_SP_AAD_CLIENT_ID }}
          AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.AZURE_EFA_FHB_SP_AAD_CLIENT_SECRET }}
          KUBECONFIG: "~/.kube/config.bremen"
        run: |
          az aks get-credentials --resource-group ${{env.AZURE_RESOURCE_GROUP}} --name ${{env.AZURE_RESOURCE_NAME}}
          kubelogin convert-kubeconfig -l spn
          kubectl config view --raw

      - name: test login
        shell: bash
        env:
          k8s_namespace: "oeffentliche-vergabe-${{matrix.stage}}"
        run: |
          kubectl get pods -n ${{env.k8s_namespace}}