name: create_release
description: "Creates a release"

inputs:
  az_sp_credentials:
    description: "Azure Service principal credentials"
    required: true
  az_sp_client_id:
    description: "ClientId of Azure Service Principal "
    required: true
  az_sp_client_secret:
    description: "Client secret of Azure Service Principal"
    required: true
  az_subscription_name:
    description: "Name of Azure Subscription to set"
    required: true
  az_aks_resource_group:
    description: "Azure Resource group of Azure Kubernetes Service"
    required: true
  az_aks_resource_name:
    description: "Name of Azure Kubernetes Service"
    required: true

runs:
  using: "composite"

  steps:

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.az_sp_credentials }}

    - name: set subscription
      shell: bash
      run: |
        az account set -n ${{inputs.az_subscription_name}}

    - name: get kubelogin
      shell: bash
      run: |
        where="~/tmp/${RANDOM}"
        mkdir -p ${where}
        wget -q -P ${where} https://github.com/Azure/kubelogin/releases/download/v0.0.20/kubelogin-linux-amd64.zip
        unzip ${where}/kubelogin-linux-amd64.zip -d ${where}
        sudo mv ${where}/bin/linux_amd64/kubelogin /usr/bin

    - name: get K8s credentials + login
      shell: bash
      run: |
        AAD_SERVICE_PRINCIPAL_CLIENT_ID=${{ inputs.az_sp_client_id }}
        AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=${{ inputs.az_sp_client_secret }}
        echo "AAD_SERVICE_PRINCIPAL_CLIENT_ID=${AAD_SERVICE_PRINCIPAL_CLIENT_ID}" >> $GITHUB_ENV
        echo "AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=${AAD_SERVICE_PRINCIPAL_CLIENT_SECRET}" >> $GITHUB_ENV

        az aks get-credentials --resource-group ${{inputs.az_aks_resource_group}} --name ${{inputs.az_aks_resource_name}}
        kubelogin convert-kubeconfig -l spn